server.port=8080

spring.datasource.url=jdbc:mysql://db:3306/tfgdb?createDatabaseIfNotExist=true
spring.datasource.username=tfguser
spring.datasource.password=tfgpassword

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

vaadin.productionMode=true
vaadin.launch-browser=false

spring.jpa.show-sql=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true